baseURL = 'https://oct.zoy.org/'
languageCode = 'en-us'
title = 'oct.zoy.org'
theme = 'PaperMod'

[imaging]
  anchor = 'Smart'
  bgColor = '#ffffff'
  hint = 'photo'
  quality = 75
  resampleFilter = 'Box'

[params]


hideFooter = false
showBreadCrumbs = true
showReadingTime = true
ShowCodeCopyButtons = true

[params.label]
  icon = "/bandana.png"

[params.profileMode]
enabled = true
title = "oct.zoy.org"
subtitle = "Pierre Baillet's Homepage"
imageUrl = "/mugshot.png"
imageTitle = "It's a-me!"
imageWidth = 144
imageHeight = 144

  [[params.profileMode.buttons]]
  name = "About"
  url = "/about"

  [[params.profileMode.buttons]]
  name = "Speaker"
  url = "/as-a-speaker"

  [[params.profileMode.buttons]]
  name = "Posts"
  url = "/posts"


  [[params.profileMode.buttons]]
  name = "Archive"
  url = "/archive"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/octplane"

[[params.socialIcons]]
name = "Github"
url = "https://github.com/octplane"

