baseURL: 'https://oct.zoy.org/'
languageCode: en-us
title: oct.zoy.org
theme: PaperMod
env: production
ignoreLogs:
  - warning-goldmark-raw-html
menu:
  main:
    - identifier: about
      name: 🪞 About
      url: /about
      weight: 1
    - identifier: compos
      name: 🎼 Compos
      url: /compos
      weight: 3
    - identifier: archives
      name: 🕰️ Post Archive
      url: /archives/
      weight: 10
    - identifier: tags
      name: 🔖 tags
      url: /tags/
      weight: 20
    - identifier: écrits
      name: 🖋️ Écrits
      url: /écrits
      weight: 40
    - identifier: écoutes
      name: 🎧 Écoutes
      url: /écoutes
      weight: 45
    - identifier: oldies
      name: 🕸️ Old stuff
      url: /old-stuff/
      weight: 50
imaging:
  anchor: Smart
  bgColor: '#ffffff'
  hint: photo
  quality: 75
  resampleFilter: Box
params:
  analytics:
    googlesiteVerificationTag: y8HjH28HsDJmfXel6OVWYfVTlOaM5Y0qt1sSIu4ncXo
  hideFooter: false
  showBreadCrumbs: true
  showReadingTime: true
  ShowCodeCopyButtons: true
  cover:
    responsiveImages: true
  mainSections:
    - posts
  label:
    icon: /bandana.png
  homeInfoParams:
    title: Welcome to my site!
    content: | 
      I'm Pierre Baillet (aka _Oct_), a programmer who's been in love with coding since my early days tinkering with an Atari ST and GFA-Basic.

      What you'll find here:

      * Bits of code and tech musings,
      * Projects that are more "works in progress" than polished gems
      * Some Music Composition
      * Thoughts shared in both English and French 🇬🇧🇫🇷

      Welcome to my little corner of the internet

      Coding isn't just what I do, it's who I am. 🖥️
  profileMode:
    enabled: false
    buttons:
      - name: Posts
        url: /posts
      - name: Archive
        url: /archive
  socialIcons:
    - name: mastodon
      url: "https://mastodon.xyz/@octplane"
    - name: Github
      url: 'https://github.com/octplane'
    - name: blogger
      url: 'https://au43demarue.blogspot.com/'
    - name: omg
      url: 'https://oct.omg.lol/'
