name: The Assembly Line
description: Le site de Pierre Baillet (octplane)
meta_description: "On y fabrique des choses inutiles,<br/>On y parle, mais pour râler,<br/>On y entend que du bruit,<br/> voit que de la poussière,<br/> et des machines incroyables..."

markdown: redcarpet
pygments: true
logo: false
paginate: 15
lang: fr

assets:         '/assets'

# Details for the RSS feed generator
url:            'http://oct.zoy.org'
author:         'Pierre Baillet'

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"


authors:
  octplane:
    display_name: Pierre Baillet
    bio: "Développeur, Administrateur, Comédien, Danseur"
    gravatar: 91deb51572c5b27f88444ded473f5726
    email: oct@zoy.org
    location: "Paris, France"
  geoff:
    display_name: Geoff Blair
    gravatar: 76dbcc74021b8039f14c7b583978b56d
    email: geoff@lostdecadegames.com
    web: http://www.geoffblair.com/
    twitter: geoffblair
    github: geoffb
