name: OCT PLANE
wname: "Pierre Baillet's Website, posts, opinions and technical stuff"
meta_description: "Le site de Pierre Baillet, aussi connu comme Octplane. On y fabrique des choses inutiles.On y parle, mais pour râler. On y entend que du bruit, oit que de la poussière, et des machines incroyables..."
meta_keywords: "french, blog, engineer, geek, ruby, scala, golang, infrastructure"
markdown: redcarpet
redcarpet:
  extensions: ["footnotes"]
highlighter: true
logo: false
paginate: 15
lang: fr

assets:         '/assets'

source: .

# Details for the RSS feed generator
url:            'http://oct.zoy.org'
author:         'Pierre Baillet'
exclude:
    - "Gemfile"
    - "Gemfile.lock"
    - "LICENSE.txt"
    - "README.md"
    - "jekyll"
    - "Rakefile"

owner_url: https://github.com/octplane
gravatar: 91deb51572c5b27f88444ded473f5726
twitter: octplane