name: OCT PLANE
wname: Pierre Baillet Website
description: Le site de Pierre Baillet (octplane)
meta_description: "On y fabrique des choses inutiles,<br/>On y parle, mais pour râler,<br/>On y entend que du bruit,<br/> voit que de la poussière,<br/> et des machines incroyables..."

markdown: redcarpet
redcarpet:
  extensions: ["footnotes"]
highlighter: true
logo: false
paginate: 15
lang: fr

assets:         '/assets'

source: .

# Details for the RSS feed generator
url:            'http://oct.zoy.org'
author:         'Pierre Baillet'
exclude:
    - "Gemfile"
    - "Gemfile.lock"
    - "LICENSE.txt"
    - "README.md"
    - "jekyll"
    - "Rakefile"

owner_url: https://github.com/octplane
gravatar: 91deb51572c5b27f88444ded473f5726
twitter: octplane